// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"database/sql"
	"e2dlabo/real_world/handlers"
	"e2dlabo/real_world/infrastructures"
	"e2dlabo/real_world/services"
)

// Injectors from injector.go:

func Initialize(db *sql.DB) (*handlers.Yeah, error) {
	infrastructuresDB := newDB(db)
	userService, err := services.NewUserService(infrastructuresDB)
	if err != nil {
		return nil, err
	}
	yeah, err := handlers.NewYeah(userService)
	if err != nil {
		return nil, err
	}
	return yeah, nil
}

// injector.go:

func newDB(db infrastructures.SqlDB) *infrastructures.DB {
	return &infrastructures.DB{
		DB: db,
	}
}
